// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDEhGc1_wP0kfGIaSenF4pZQigxvnQch2s',
    appId: '1:819767024947:web:346f67c5c12185c86ab246',
    messagingSenderId: '819767024947',
    projectId: 'socialflutterapp-38978',
    authDomain: 'socialflutterapp-38978.firebaseapp.com',
    storageBucket: 'socialflutterapp-38978.appspot.com',
    measurementId: 'G-QKZJMGNTQG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCXEWdfFfssdjNLn5UFgzY3kfwLESaQNEw',
    appId: '1:819767024947:android:ee0fbe04273957126ab246',
    messagingSenderId: '819767024947',
    projectId: 'socialflutterapp-38978',
    storageBucket: 'socialflutterapp-38978.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCSZgdaYlfFuCBXOg-DkCydXFa2evM1BLs',
    appId: '1:819767024947:ios:aed0b0fb16cdc30b6ab246',
    messagingSenderId: '819767024947',
    projectId: 'socialflutterapp-38978',
    storageBucket: 'socialflutterapp-38978.appspot.com',
    androidClientId: '819767024947-jdtujgh1anjap06a1ti6f9c3ql6n1huv.apps.googleusercontent.com',
    iosClientId: '819767024947-o806u283iepdnus9frm5errmthq0g9as.apps.googleusercontent.com',
    iosBundleId: 'com.example.socialProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCSZgdaYlfFuCBXOg-DkCydXFa2evM1BLs',
    appId: '1:819767024947:ios:aed0b0fb16cdc30b6ab246',
    messagingSenderId: '819767024947',
    projectId: 'socialflutterapp-38978',
    storageBucket: 'socialflutterapp-38978.appspot.com',
    androidClientId: '819767024947-jdtujgh1anjap06a1ti6f9c3ql6n1huv.apps.googleusercontent.com',
    iosClientId: '819767024947-o806u283iepdnus9frm5errmthq0g9as.apps.googleusercontent.com',
    iosBundleId: 'com.example.socialProject',
  );
}
